---
- name: Retrieve admin credentials
  hosts: localhost
  gather_facts: no
  tasks:
  - name: add instance host with machine credential in inventory
    add_host:
      name: "instance"
      admin_username: "{{ansible_user}}"
      admin_password: "{{ansible_password}}"
      
  - name: Report endpoints
    debug:
      msg: "Username: {{ admin_username }} Password: {{ admin_password }}"
